version: "3.6"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ken/ampcamp-web
    volumes:
      - ".:/usr/src/app"
      - ".:/usr/src/app/node_modules"
      ports:
        - "80:3000"
      environment:
        -NODE_ENV=production
